:filename: main/jbake/content/workshops/javaland2020.adoc
:jbake-type: page
:jbake-title: Dukecon Mobile
:jbake-status: published

= Kotlin multiplatform workshop

Wir bauen gemeinsam eine auf der DukeCon Kotlin Native Library basierende App, die das Vortragsprogramm der JavaLand anzeigen kann. Hier lernt ihr Kotlin/Native und Kotlin Multiplatform kennen und erfahrt, wie man eine KLib baut, sie konsumiert und auf unterschiedlichen Zielplattformen einsetzt.

== Workshop

https://programm.javaland.eu/2020/#/scheduledEvent/591631[Javaland 2020 Workshop zu Kotlin/Native und -Multiplatform]

=== Referenten

https://harakal.de[Michal Harakal]

https://programm.javaland.eu/2020/#/speaker/363284[Falk Sippach]

== Voraussetzungen:
Ein Laptop mit IDE nach Wahl (IntelliJ, Eclipse etc.) und Android Studio, Android SDK, Emulator/Smartphone oder Apple Mac mit *Xcode*.

=== Updates

22.02.2020 danke an https://twitter.com/buk/status/1231289200890253313?s=21 es ist *Xcode*

[quote, Chris Espinosa]
____
"The C language is case-sensitive. Compilers are case-sensitive. The Unix command line, ufs, and nfs file systems are case-sensitive. I'm case-sensitive too, especially about product names. The IDE is called Xcode. Big X, little c. Not XCode or xCode or X-Code. Remember that now."
____
