#source 'https://github.com/CocoaPods/Specs.git'

target 'iosApp' do
    # https://stackoverflow.com/a/41210375/211886
    use_frameworks!
    pod 'dukecon_umbrella', :path => '../../shared/dukecon_umbrella'
end

target 'iosAppTests' do
  pod 'dukecon_umbrella', :path => '../../shared/dukecon_umbrella'
end

